### PR TITLE
Support rails@6.1, fix #2

### LINKED ISSUE #2: Update needed for Rails 6.1
It seems the method of accessing db config has changed: https://github.com/rails/rails/commit/4ee9dab316296ee96629f2bffbab756a163d1b49

Current behavior with 6.1:
```
NameError: undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007fb245d69238>
Did you mean?  configuration_hash
gems/pgreset-0.1.1/lib/pgreset.rb:14:in `drop'
```

### PR DESCRIPTION
**Pull request by layerssss**
This is an addition for https://github.com/dafalcon/pgreset/pull/3, adding backward compatibility.

### CODE REVIEW

**Comment by layerssss** [comment]
Now with some tests and patches, it can finally be working with both a rails 6.1 instance and a rails 6.0.2 instance. In the absence of CI, please manually test and review this carefully.
