### PR TITLE
Fix issue #2

### LINKED ISSUE #2: Update needed for Rails 6.1
It seems the method of accessing db config has changed: https://github.com/rails/rails/commit/4ee9dab316296ee96629f2bffbab756a163d1b49

Current behavior with 6.1:
```
NameError: undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007fb245d69238>
Did you mean?  configuration_hash
gems/pgreset-0.1.1/lib/pgreset.rb:14:in `drop'
```

### PR DESCRIPTION
**Pull request by ekampp**
This changes configuration -> configuration_hash since Rails 6.1 has changed the name in ActiveRecord.

### CODE REVIEW

**Comment by dafalcon** [comment]
Thank you for submitting this!!  Do the changes still work with older versions of Rails, pre 6.1?

**Comment by ekampp** [comment]
No, they don't. I can try to work that in. Are there tests i can run to verify the changes? Perhaps in Travis or CircleCI or similar?

**Comment by layerssss** [comment]
@dafalcon @ekampp I've added a change to make it work with older version as it is now. I'm gonna try it in a few rails apps with that in the next few minutes.

**Comment by layerssss** [comment]
@ekampp Also I found in my rails app the "database" key in `configuration_hash` is a symbol `:database` instead of string. So I've put both keys in the code.

**Comment by ekampp** [comment]
@layerssss, consider calling either `deep_symbolize_keys` or `deep_stringify_keys` or `with_indifferent_access` (might be deprecated) on the hash to prevent key type from breaking this gem.
